version: "3.8"

services:
 

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: always
    # environment:
    #    MONGO_INITDB_ROOT_USERNAME: root
    #    MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - "./dev/mongodb/primary:/data/db"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mongo-replica-set" ]



  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
  #     ME_CONFIG_BASICAUTH_USERNAME : root
  #     ME_CONFIG_BASICAUTH_PASSWORD : example
 

  