version: "3"

vars:
  AWS_REGION: ap-northeast-1
  LOCALSTACK_ENDPOINT: http://localhost:4566

tasks:
  local-up:
    cmds: 
     - docker-compose up -d  
     - Powershell.exe -File mongo-init.ps1
    desc: "[local] 建立本地開發環境"
  local-down:
    cmds: 
     - docker-compose down
    desc: "[local] 關閉本地開發環境"
      